server:
    port:8080

#database control
spring:
    datasource:
      url: jdbc:mysql://192.168.101.15:3306/mk-swcenter?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: swcenter
      password: 123456
      #module agent
      thymeleaf:
      encoding: UTF-8
      #suffix: .html
      #prefix: classpath:/templates/

mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml
    type-aliases-package: com.mksun.swcenter.entity